#!/bin/bash

# Bluetoothctl Command Help Script

echo "Bluetoothctl Command Help:"
echo "--------------------------"
echo "1. Start bluetoothctl:                   bluetoothctl"
echo "2. List available controllers:            list"
echo "3. Select a specific controller:          select <controller_mac_address>"
echo "4. Show controller details:               show"
echo "5. Power the controller on/off:           power on | power off"
echo "6. Scan for devices:                     scan on | scan off"
echo "7. List paired devices:                  paired-devices"
echo "8. Pair with a device:                   pair <device_mac_address>"
echo "9. Trust a device:                       trust <device_mac_address>"
echo "10. Remove trust from a device:          untrust <device_mac_address>"
echo "11. Connect to a device:                 connect <device_mac_address>"
echo "12. Disconnect from a device:            disconnect <device_mac_address>"
echo "13. Remove (unpair) a device:            remove <device_mac_address>"
echo "14. Set the controller as discoverable:  discoverable on | discoverable off"
echo "15. Set the controller as pairable:      pairable on | pairable off"
echo "16. Get info about a device:             info <device_mac_address>"
echo "17. Agent-related commands:              agent on | agent off | default-agent"
echo "18. Exit bluetoothctl:                   quit"
echo "--------------------------"
echo "Note: To use these commands, first enter the 'bluetoothctl' interface. After that, you can input the commands as described above."
